x-airflow-common-override: &airflow-common-override
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  volumes:
    - ${MY_AIRFLOW_PROJ_DIR:-.}/src:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins

services:
  airflow-webserver:
    <<: *airflow-common-override
  airflow-scheduler:
    <<: *airflow-common-override
  airflow-worker:
    <<: *airflow-common-override
  airflow-triggerer:
    <<: *airflow-common-override
  airflow-init:
    <<: *airflow-common-override
